# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.33.dev71+gae9ebbb.d20220623'
__version_tuple__ = version_tuple = (0, 1, 33, 'dev71', 'gae9ebbb.d20220623')
