# Generated by Django 2.1 on 2018-10-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notify_on_callback',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notify_on_create_model',
        ),
        migrations.AddField(
            model_name='notification',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
